/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mauro.app;

import com.mauro.librodeclases.Alumno;
import com.mauro.librodeclases.Apoderado;
import com.mauro.librodeclases.Colegio;
import com.mauro.librodeclases.Curso;
import com.mauro.librodeclases.Ramo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;

/**
 * Ventana principal de la GUI del Libro de clases. Por el momento queda
 * limitado a registrar s\u00f3lo un colegio, pero queda abierto a cambios
 * futuros.
 *
 * @author Mauricio Acencio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * \u00cdndice seleccionado de la lista de cursos: 0: 1ºA; 1: 1ºB; 2: 2ºA;
     * 3: 2ºB; 4: 3ºA; 5: 3ºB; 6: 4ºA; 7: 4ºB 8: 5ºA; 9: 5ºB; 10: 6ºA; 11: 6ºB;
     * 12: 7ºA; 13: 7ºB; 14: 8ºA; 15: 8ºB
     */
    public static byte seleccion;

    /**
     * \u00cdndice seleccionado de la lista de ramos del curso actualmente
     * seleccionado.
     */
    public static int numRamo;

    /**
     * \u00cdndice seleccionado de la lista de alumnos del curso actualmente
     * seleccionado.
     */
    public static int numAlumno;

    /**
     * Lista de apoderados, conexi\u00f3n directa.
     */
    public static ArrayList<Apoderado> apoderados;

    /**
     * Colegio ascociado a esta ventana
     */
    public static Colegio colegio;

    /**
     * Creates new form Ventana
     */
    public Principal() {
        initComponents();
        if (seleccion > 0) {
            Curso get = colegio.cursos.get(seleccion);
            nivelCurso.setValue(get.getNivel());
            boolean esA = get.getLetra() == 'A';
            cursoA.setSelected(esA);
            cursoB.setSelected(!esA);
        }
        setPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenu4 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        letraCurso = new javax.swing.ButtonGroup();
        jPanelSeleccionador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nivelCurso = new javax.swing.JSpinner();
        cursoA = new javax.swing.JRadioButton();
        cursoB = new javax.swing.JRadioButton();
        botonCurso = new javax.swing.JButton();
        listaAlumnos = new javax.swing.JComboBox<>();
        listaRamos = new javax.swing.JComboBox<>();
        jPanelRamo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreRamo = new javax.swing.JLabel();
        nombreProfesor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modeloActv = new DefaultListModel();
        listaActividades = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        agregarActividad = new javax.swing.JButton();
        detalleActividad = new javax.swing.JButton();
        jPanelAlumno = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreAlumno = new javax.swing.JLabel();
        nombreApoderado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        matriculaAlumno = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        agregarAnotacion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        modeloAnot = new DefaultListModel();
        listaAnotaciones = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        listaNotas = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        notaPromedio = new javax.swing.JLabel();
        agregarNota = new javax.swing.JButton();
        nota1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nota2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        agregarAsistencia = new javax.swing.JButton();
        verAsistencia = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        jMenuRegistro = new javax.swing.JMenu();
        itemGuardar = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        jMenuNuevo = new javax.swing.JMenu();
        nuevoAlumno = new javax.swing.JMenuItem();
        nuevoRamo = new javax.swing.JMenuItem();
        jMenuInfrome = new javax.swing.JMenu();
        itemInfGeneralApods = new javax.swing.JCheckBoxMenuItem();
        itemInfApodPupilos = new javax.swing.JCheckBoxMenuItem();
        itemInforme = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libro de Clases");
        setResizable(false);

        jLabel1.setText("Curso:");

        nivelCurso.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)1), Byte.valueOf((byte)1), Byte.valueOf((byte)8), Byte.valueOf((byte)1)));

        letraCurso.add(cursoA);
        cursoA.setSelected(true);
        cursoA.setText("A");

        letraCurso.add(cursoB);
        cursoB.setText("B");

        botonCurso.setText("Ir");
        botonCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCursoActionPerformed(evt);
            }
        });

        listaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAlumnosActionPerformed(evt);
            }
        });

        listaRamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaRamosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSeleccionadorLayout = new javax.swing.GroupLayout(jPanelSeleccionador);
        jPanelSeleccionador.setLayout(jPanelSeleccionadorLayout);
        jPanelSeleccionadorLayout.setHorizontalGroup(
            jPanelSeleccionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nivelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cursoA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cursoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaRamos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelSeleccionadorLayout.setVerticalGroup(
            jPanelSeleccionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSeleccionadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nivelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursoA)
                    .addComponent(cursoB)
                    .addComponent(botonCurso)
                    .addComponent(listaRamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelRamo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Ramo:");

        nombreRamo.setText("jLabel3");

        nombreProfesor.setText("jLabel3");

        jLabel3.setText("Profesor:");

        listaActividades.setModel(modeloActv);
        jScrollPane1.setViewportView(listaActividades);

        jLabel6.setText("Actividades:");

        agregarActividad.setText("Agregar...");
        agregarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActividadActionPerformed(evt);
            }
        });

        detalleActividad.setText("Ver más...");
        detalleActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRamoLayout = new javax.swing.GroupLayout(jPanelRamo);
        jPanelRamo.setLayout(jPanelRamoLayout);
        jPanelRamoLayout.setHorizontalGroup(
            jPanelRamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelRamoLayout.createSequentialGroup()
                        .addGroup(jPanelRamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelRamoLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nombreProfesor))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRamoLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nombreRamo)))
                            .addComponent(jLabel6)
                            .addGroup(jPanelRamoLayout.createSequentialGroup()
                                .addComponent(agregarActividad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detalleActividad)))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelRamoLayout.setVerticalGroup(
            jPanelRamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreRamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProfesor)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarActividad)
                    .addComponent(detalleActividad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Alumno:");

        jLabel5.setText("Apoderado:");

        nombreAlumno.setText("jLabel6");

        nombreApoderado.setText("jLabel7");

        jLabel7.setText("Matrícula:");

        matriculaAlumno.setText("jLabel8");

        jLabel8.setText("Anotaciones / observaciones:");

        agregarAnotacion.setText("Agregar...");
        agregarAnotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAnotacionActionPerformed(evt);
            }
        });

        listaActividades.setModel(modeloAnot);
        jScrollPane3.setViewportView(listaAnotaciones);

        jLabel9.setText("Notas:");

        jLabel10.setText("Promedio:");

        notaPromedio.setText("-,-");

        agregarNota.setText("Agregar:");
        agregarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarNotaActionPerformed(evt);
            }
        });

        nota1.setText("1");
        nota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nota1KeyTyped(evt);
            }
        });

        jLabel12.setText(",");

        nota2.setText("0");
        nota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nota2KeyTyped(evt);
            }
        });

        jLabel11.setText("Registro de asistencias:");

        agregarAsistencia.setText("Agregar...");
        agregarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAsistenciaActionPerformed(evt);
            }
        });

        verAsistencia.setText("Ver");
        verAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlumnoLayout = new javax.swing.GroupLayout(jPanelAlumno);
        jPanelAlumno.setLayout(jPanelAlumnoLayout);
        jPanelAlumnoLayout.setHorizontalGroup(
            jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notaPromedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                        .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreAlumno))
                            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreApoderado))
                            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matriculaAlumno))
                            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(agregarAnotacion)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verAsistencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agregarAsistencia)))
                .addContainerGap())
        );
        jPanelAlumnoLayout.setVerticalGroup(
            jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombreAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(matriculaAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombreApoderado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(agregarAnotacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(listaNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(notaPromedio)
                    .addComponent(agregarNota)
                    .addComponent(nota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(nota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(agregarAsistencia)
                    .addComponent(verAsistencia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuRegistro.setText("Registro");

        itemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarActionPerformed(evt);
            }
        });
        jMenuRegistro.add(itemGuardar);

        itemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        jMenuRegistro.add(itemSalir);

        menu.add(jMenuRegistro);

        jMenuNuevo.setText("Nuevo...");

        nuevoAlumno.setText("Alumno...");
        nuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAlumnoActionPerformed(evt);
            }
        });
        jMenuNuevo.add(nuevoAlumno);

        nuevoRamo.setText("Ramo...");
        nuevoRamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoRamoActionPerformed(evt);
            }
        });
        jMenuNuevo.add(nuevoRamo);

        menu.add(jMenuNuevo);

        jMenuInfrome.setText("Infrome");

        itemInfGeneralApods.setSelected(true);
        itemInfGeneralApods.setText("Informe general para apoderados");
        jMenuInfrome.add(itemInfGeneralApods);

        itemInfApodPupilos.setText("Apoderados con más de un pupilo");
        itemInfApodPupilos.setEnabled(false);
        jMenuInfrome.add(itemInfApodPupilos);

        itemInforme.setText("Generar Infrome(s)");
        itemInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInformeActionPerformed(evt);
            }
        });
        jMenuInfrome.add(itemInforme);

        menu.add(jMenuInfrome);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSeleccionador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelSeleccionador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        try {
            Transformador.guardar();
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_itemGuardarActionPerformed

    private void itemInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInformeActionPerformed
        try {
            if (itemInfGeneralApods.isSelected()) {
                Transformador.generarInforme(1);
            }
            if (itemInfApodPupilos.isSelected()) {
                Transformador.generarInforme(2);
            }
        } catch (Exception e) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_itemInformeActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void botonCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCursoActionPerformed
        byte n = (byte) nivelCurso.getValue();
        if (n < 1) {
            nivelCurso.setValue(1);
        } else if (n > 8) {
            nivelCurso.setValue(8);
        }
        setCurso((byte) nivelCurso.getValue());
    }//GEN-LAST:event_botonCursoActionPerformed

    private void nuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAlumnoActionPerformed
        agregarAlumno();
    }//GEN-LAST:event_nuevoAlumnoActionPerformed

    private void nuevoRamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoRamoActionPerformed
        agregarRamo();
    }//GEN-LAST:event_nuevoRamoActionPerformed

    private void agregarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActividadActionPerformed
        agregarActividad();
    }//GEN-LAST:event_agregarActividadActionPerformed

    private void detalleActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleActividadActionPerformed
        new VerActividad(listaActividades.getSelectedIndex()).setVisible(true);
    }//GEN-LAST:event_detalleActividadActionPerformed

    private void listaRamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaRamosActionPerformed
        numRamo = listaRamos.getSelectedIndex();
        setTextoRamo();
    }//GEN-LAST:event_listaRamosActionPerformed

    private void agregarAnotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAnotacionActionPerformed
        agregarAnotacion();
    }//GEN-LAST:event_agregarAnotacionActionPerformed

    private void agregarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAsistenciaActionPerformed
        agregarAsistencia();
    }//GEN-LAST:event_agregarAsistenciaActionPerformed

    private void agregarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarNotaActionPerformed
        agregarNota();
    }//GEN-LAST:event_agregarNotaActionPerformed

    private void verAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAsistenciaActionPerformed
        new VerAsistencia().setVisible(true);
    }//GEN-LAST:event_verAsistenciaActionPerformed

    private void listaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAlumnosActionPerformed
        numAlumno = listaAlumnos.getSelectedIndex();
        setTextoAlumno();
    }//GEN-LAST:event_listaAlumnosActionPerformed

    private void nota1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nota1KeyTyped
        int n = Character.getNumericValue(evt.getKeyChar());
        if (n < 1 || n > 7) {
            evt.consume();
            if (nota1.getColumns() == 0) {
                nota1.setText("1");
            }
        } else if (nota1.getColumns() > 1) {
            nota1.setText(Integer.toString(n));
        }
    }//GEN-LAST:event_nota1KeyTyped

    private void nota2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nota2KeyTyped
        int n = Character.getNumericValue(evt.getKeyChar());
        if (n < 0 || n > 7) {
            evt.consume();
            if (nota2.getColumns() == 0) {
                nota2.setText("0");
            }
        } else if (nota2.getColumns() > 1) {
            nota2.setText(Integer.toString(n));
        }
        if (nota1.getText().equals(7) && n == 0) {
            nota2.setText("0");
        }
    }//GEN-LAST:event_nota2KeyTyped

    private void agregarAlumno() {
        this.dispose();
        new NuevoAlumno().setVisible(true);
    }

    private void agregarRamo() {
        this.dispose();
        new NuevoRamo().setVisible(true);
    }

    private void agregarActividad() {
        this.dispose();
        new NuevaActividad().setVisible(true);
    }

    private void agregarAnotacion() {
        this.dispose();
        new NuevaAnotacion().setVisible(true);
    }

    private void agregarAsistencia() {
        this.dispose();
        new NuevaAsistencia().setVisible(true);
    }

    private void agregarNota() {
        float nota = Integer.parseInt(nota1.getText())
                + Float.parseFloat(nota2.getText()) / 10;
        colegio.cursos.get(seleccion).alumnos.get(numAlumno).notas.add(nota);
        setTextoAlumno();
    }

    private void setCurso(byte i) {
        seleccion = (byte) ((2 * i) - (cursoA.isSelected() ? 2 : 1));
        setPanel();
    }

    private void setPanel() {
        listaAlumnos.removeAllItems();
        listaAlumnos.setEnabled(!colegio.cursos.get(seleccion).alumnos.isEmpty());
        colegio.cursos.get(seleccion).alumnos.forEach((alumno) -> {
            listaAlumnos.addItem(alumno.getNombre());
        });
        listaAlumnos.setSelectedIndex(colegio.cursos.get(seleccion).alumnos.isEmpty()
                ? -1 : numAlumno);
        setTextoAlumno();
        listaRamos.removeAllItems();
        listaRamos.setEnabled(!colegio.cursos.get(seleccion).ramos.isEmpty());
        colegio.cursos.get(seleccion).ramos.forEach((ramo) -> {
            listaRamos.addItem(ramo.getNombre());
        });
        listaRamos.setSelectedIndex(colegio.cursos.get(seleccion).ramos.isEmpty()
                ? -1 : numRamo);
        setTextoRamo();
    }

    private void setTextoRamo() {
        modeloActv.clear();
        if (listaRamos.getSelectedIndex() == -1) {
            nombreRamo.setText("");
            nombreProfesor.setText("");
            detalleActividad.setEnabled(false);
            agregarActividad.setEnabled(false);
            nuevoAlumno.setEnabled(false);
        } else {
            Ramo r = colegio.cursos.get(seleccion).ramos.get(numRamo);
            nombreRamo.setText(r.getNombre());
            nombreProfesor.setText(r.getProfesor().getNombre());
            r.planificacion.forEach((actv) -> {
                String[] f = actv.getFecha();
                modeloActv.addElement(f[0] + "/" + f[1] + "/" + f[2] + ": " + actv.getNombre());
            });
            listaActividades.setModel(modeloActv);
            detalleActividad.setEnabled(!r.planificacion.isEmpty());
            nuevoAlumno.setEnabled(true);
        }
    }

    private void setTextoAlumno() {
        modeloAnot.removeAllElements();
        listaNotas.removeAllItems();
        if (listaAlumnos.getSelectedIndex() == -1) {
            nombreAlumno.setText("");
            matriculaAlumno.setText("");
            nombreApoderado.setText("");
            agregarAnotacion.setEnabled(false);
            notaPromedio.setText("-,-");
            agregarNota.setEnabled(false);
            verAsistencia.setEnabled(false);
            agregarAsistencia.setEnabled(false);
        } else {
            Alumno al = colegio.cursos.get(seleccion).alumnos.get(numAlumno);
            nombreAlumno.setText(al.getNombre());
            matriculaAlumno.setText(al.getMatricula());
            nombreApoderado.setText(al.apoderado.getNombre());
            al.anotaciones.forEach((anot) -> {
                modeloAnot.addElement(anot.toString());
            });
            listaAnotaciones.setModel(modeloAnot);
            agregarAnotacion.setEnabled(true);
            if (al.notas.isEmpty()) {
                notaPromedio.setText("-,-");
            } else {
                float sum = 0;
                for (Float nota : al.notas) {
                    listaNotas.addItem(String.format("%.1f", nota));
                    sum += nota;
                }
                notaPromedio.setText(String.format("%.1f", sum / al.notas.size()));
            }
            agregarNota.setEnabled(true);
            verAsistencia.setEnabled(!al.registro.isEmpty());
            agregarAsistencia.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        seleccion = 0;
        numRamo = 0;
        apoderados = new ArrayList<>();
        if (new java.io.File("data\\libro.xml").exists()) {
            String info = "Existe un registro anterior.\n¿Desea poblarlo ahora?";
            if (JOptionPane.showConfirmDialog(null, info, "Carga", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    SAXParser sp = SAXParserFactory.newInstance().newSAXParser();
                    Poblador p = new Poblador();
                    sp.parse("data\\libro.xml", p);
                } catch (Exception ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (colegio == null) {
            colegio = new Colegio("GeorgeChaytor", "Av. Gabriela Mistra 43589");
            colegio.generarCursos();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarActividad;
    private javax.swing.JButton agregarAnotacion;
    private javax.swing.JButton agregarAsistencia;
    private javax.swing.JButton agregarNota;
    private javax.swing.JButton botonCurso;
    private javax.swing.JRadioButton cursoA;
    private javax.swing.JRadioButton cursoB;
    private javax.swing.JButton detalleActividad;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JCheckBoxMenuItem itemInfApodPupilos;
    private javax.swing.JCheckBoxMenuItem itemInfGeneralApods;
    private javax.swing.JMenuItem itemInforme;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuInfrome;
    private javax.swing.JMenu jMenuNuevo;
    private javax.swing.JMenu jMenuRegistro;
    private javax.swing.JPanel jPanelAlumno;
    private javax.swing.JPanel jPanelRamo;
    private javax.swing.JPanel jPanelSeleccionador;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.ButtonGroup letraCurso;
    private javax.swing.JList<String> listaActividades;
    private DefaultListModel modeloActv;
    private javax.swing.JComboBox<String> listaAlumnos;
    private javax.swing.JList<String> listaAnotaciones;
    private DefaultListModel modeloAnot;
    private javax.swing.JComboBox<String> listaNotas;
    private javax.swing.JComboBox<String> listaRamos;
    private javax.swing.JLabel matriculaAlumno;
    private javax.swing.JMenuBar menu;
    private javax.swing.JSpinner nivelCurso;
    private javax.swing.JLabel nombreAlumno;
    private javax.swing.JLabel nombreApoderado;
    private javax.swing.JLabel nombreProfesor;
    private javax.swing.JLabel nombreRamo;
    private javax.swing.JTextField nota1;
    private javax.swing.JTextField nota2;
    private javax.swing.JLabel notaPromedio;
    private javax.swing.JMenuItem nuevoAlumno;
    private javax.swing.JMenuItem nuevoRamo;
    private javax.swing.JButton verAsistencia;
    // End of variables declaration//GEN-END:variables
}
